# Generated by Django 4.2.13 on 2024-07-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'М'), ('F', 'Ж')], max_length=1, verbose_name='Пол'),
        ),
    ]
