# Generated by Django 4.2.13 on 2024-07-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='reduction',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Сокращение'),
        ),
    ]
